name: "On Push"
on:
  push:
    branches:
      - "main"

jobs:
  changes:
    runs-on: ubuntu-latest
    name: detect-changes
    outputs:
      working-dir: ${{ steps.detect.outputs.changes }}
      versions: ${{ steps.get_filters.outputs.versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Filters
        id: get_filters
        uses: LexisNexis-RBA/rsg-gh-action-parse-working-directory@v1.1.0
        with:
          file: "./filters.yaml"

      - uses: dorny/paths-filter@v2
        id: detect
        with:
          filters: ${{ steps.get_filters.outputs.working-directory }}

  Apply:
    needs: [changes]
    name: "${{ matrix.working-directory }}"
    uses: LexisNexis-RBA/rsg-terragrunt-workflows/.github/workflows/terragrunt-apply.yaml@main
    if: needs.changes.outputs.working-dir != '[]'
    strategy:
      matrix:
        working-directory: ${{ fromJSON(needs.changes.outputs.working-dir) }}
      max-parallel: 1
    with:
      working_directory: "${{ matrix.working-directory }}"
      workspace_name: "${{ matrix.working-directory }}"
      rba_terraform_modules_auth: true
      workflow_key: "${{ matrix.working-directory }}"
      terraform_version: ${{ fromJSON(needs.changes.outputs.versions)[format('{0}-terraform-version', matrix.working-directory)] }}
      terragrunt_version: ${{ fromJSON(needs.changes.outputs.versions)[format('{0}-terragrunt-version', matrix.working-directory)] }}
      runner_static_ip_from_range: ${{ fromJSON(needs.changes.outputs.versions)[format('{0}-use-static-runner', matrix.working-directory)] }}
      github_environment: deployment
      tfsec: true
      tfsec_version: latest
      aws_backend_region: us-east-1
      aws_backend_role: arn:aws:iam::652170849784:role/github-actions/iac-${{ github.event.repository.name }}-rw
      access_credentials_ttl: ${{ fromJSON(vars.DEFAULT_TTL) }}
      vault: true
      vault_address: https://vault.cluster.us-vault-prod.azure.lnrsg.io/
      vault_path: github-actions
      vault_role: ${{ github.event.repository.name }}-rw
      env: |
        TF_VAR_admin_group_object_ids = "${{ vars.AZURE_AD_COMMERCIAL_SP_GROUP_ID || '' }}"[*]
    secrets: inherit 